### ISSUE TITLE
Questions about the shallow copy in hashcons and various extras

### ISSUE THREAD

**Issue by mrakgr** [backtracking/ocaml-hashcons#4]
```
      match Weak.get_copy bucket i with
        | Some v when v.node = d ->
	    begin match Weak.get bucket i with
              | Some v -> v
              | None -> loop (i+1)
            end
        | _ -> loop (i+1)
```
The above fragment starts at line 120 in [`hashcons.ml`](https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L120). I have 3 questions:

1) Is the shallow copy necessary? Unfortunately, in .NET the shallow copy is a restricted member of an object so I cannot call it from the outside. Would the following rewrite without the shallow copy work?
```
            match bucket.[i] with
            | Some v when v.node = d -> v
            | _ -> loop (i+1)
```

2) Does it really improve performance? I am guessing this is why it has been written this way, but I am skeptical that copying a object and then comparing it, before checking the bucket again is more efficient than just comparing it. Also, I am not sure about OCaml, but in .NET I am reading that the in-built shallow copy has some overhead compared to the manual one so that is one more thing to watch out for.

3) The way the None case is implemented is somewhat nonsensical to me since instead of looping to the next object, presumably it would be better to reuse the current empty slot in the bucket since it is already known that the equality check succeeded. I am assuming that the node should be unique in the bucket and that there will be no need to compare it with the others. Is there something I am missing here?

**Comment by mrakgr** [comment]
Not related to the shallow copy, but on [line 110](https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L110) based on the [Hashtbl documentation](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Hashtbl.html) the logical and to zero out the sign bit is unnecessary since the hash will always associate a non-negative integer.

Having it there did help me since I would have probably rewritten it incorrectly since the .NET's inbuilt hashing can return a negative integer.

**Comment by mrakgr** [comment]
Let me add one more while I am at it.

In `let next_sz n = min (3*n/2 + 3) (Sys.max_array_length - 1)` and `let newsz = min (sz + 3) (Sys.max_array_length - 1) in` you are using the `max_array_length - 1`. Why the `-1`?

**Comment by mrakgr** [comment]
On [line 390](https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L390), there is a typo in the comment. `by branching only one the relevant bits (i.e. the ones for which` should be `by branching only on one of the relevant bits (i.e. the ones for which`. There are `on` and `of` missing.

I wanted to ask since I am cleaning up the comments for the F# version, in what kind of format are they?

**Comment by mrakgr** [comment]
On [line 416](https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L416), in `value of $2^2 = 4$), with prefix [0b01 = 1].` I am a bit confused how `0b01` comes to equal `1`. Shouldn't `0b01` be `2`? Perhaps it was meant be `0b1 = 1`.

Edit 2: In my last edit, I said to ignore what I wrote above since it should be read right to left, but given that the library is based on a little endian implementation, the least significant bits should come near the beginning and it in fact should be read left to right for consistency.

**Comment by mrakgr** [comment]
Sorry about the barrage of questions. Based on the paper, I have one observation.
```
    let rec mem (k: ConsedNode<_>) = function
        | Empty -> false
        | Leaf(j,_) -> k.Tag = j.Tag
        | Branch(_, m, l, r) -> mem k (if zero_bit k.Tag m then l else r)
```
The above is a straightforward translation from Ocaml, but in Okasaki's paper I noticed that they are taking the prefix field into consideration as well. Therefore a straightforward improvement would be to redesign the function as such.
```
    let rec mem (k: ConsedNode<_>) = function
        | Empty -> false
        | Leaf(j,_) -> k.Tag = j.Tag
        | Branch(p, m, l, r) -> 
            if match_prefix k.Tag p m = false then false
            else mem k (if zero_bit k.Tag m then l else r)
```
This seems like a particularly important optimization for Map's `find` which is nearly the same as the `mem` above. It might be worth incorporating into the OCaml example.

Edit: Though now I see the paper does mention that if most queries are expected to be successful then it would be slightly more efficient to eliminate the prefix check.

**Comment by mrakgr** [comment]
One last question - I've been trying to find some benchmarks on Patricia trees and having no luck. I've gone through Okasaki's original paper and it is quite inconclusive with regards to whether the Patricia trees should even be used for storing integers versus other kinds of structures.

Of what little I can find, on the Haskell's [IntMap](https://hackage.haskell.org/package/containers-0.5.10.2/docs/Data-IntMap.html) page, it says that the IntMap which is based on big endian Patricia trees is significantly faster for deletion and insertion in addition to the union and intersection operations, but my compiler is not in Haskell so I can't really pick that up.

My feeling is that there is too little evidence to conclude whether Patricia trees should be favored over other structures.

Have you done any kind of benchmarking of Patricia trees against other kinds of data structures? If so I'd be curious as to what your findings were even if it is off hand.

**Comment by backtracking** [comment]
You're right, thanks.

(Note that in the functorial version we need to do it, as the
user-provided hash function may not always return nonnegative values.)

Jean-Christophe

**Comment by backtracking** [comment]
The documentation of Weak.create says

       Raise Invalid_argument if n is negative  or
       greater than Sys.max_array_length -1 .


--
Jean-Christophe

**Comment by backtracking** [comment]
> On line 390
> <https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L390>,
> there is a typo in the comment. |by branching only one the relevant bits
> (i.e. the ones for which| should be |by branching only on one of the
> relevant bits (i.e. the ones for which|. There are |on| and |of| missing.

Thanks for spotting the typo. Actually, it should be

      by branching only on the relevant bits (i.e. the ones for which
      there is at least one element in each subtree)

since you can branch on several bits at once.

> I wanted to ask since I am cleaning up the comments for the F# version,
> in what kind of format are they?

These are comments for my own tool ocamlweb, a literate programming tool
inspired from Knuth's web tool. The contents of comments is LaTeX, with
brackets used to quote pieces of OCaml code.

Here is an example of output:
https://www.lri.fr/~filliatr/ftp/ocaml/ds/pt.pdf

This tool is seldom used by others than myself.

--
Jean-Christophe

**Comment by backtracking** [comment]
When writing numbers in base 2, most significant digits come first, as
with other radixes (but I guess you know that already :-)). So indeed,
0b01 is 1.

The leading zero is intentionally written here to emphasize the fact we
are comparing two digits at this branching node.

--
Jean-Christophe

**Comment by mrakgr** [comment]
One more question.

`let unsigned_lt n m = n >= 0 && (m < 0 || n < m)` 

Your library is using the `unsigned_lt` to compare branching bits, but Okasaki's paper does not and uses standard operators instead. The simplest explanation that I can think of is that SML/NJ uses unsigned ints by default, but that seems unlikely. But neither does it seem likely for there to be an error like that in the paper, so what is the reason?

Also, instead of doing comparisons using `unsigned_lt`, wouldn't it be simpler to use unsigned integer keys instead?

**Comment by backtracking** [comment]
In Okasaki and Gill's paper
http://ittc.ku.edu/~andygill/papers/IntMap98.pdf
there are actually both versions (with and without the match_prefix
test) and a comment saying

  if most queries are expected to be successful, then it is slightly
more efficient to eliminate the matchPrefix test

So I guess I followed this way when I first implemented Patricia trees
(back in 2000) and then forgot about it in later implementations such as
the one in Hashcons.

--
Jean-Christophe

**Comment by backtracking** [comment]
This is fixing a bug in Okasaki & Gill's paper (when the branching bit
is the sign bit). The bug was found by Jan Midtgaard using QuickCheck
and I subsequently fixed it using this unsigned_lt function.

If you are curious, the bug finding is described in this paper:
http://janmidtgaard.dk/papers/Midtgaard%3a17.pdf

But you're right: I should be more explicit in the comment that this is
fixing a bug in the original paper.

--
Jean-Christophe

**Comment by backtracking** [comment]
That's a very good question: some years ago, I made lots of experiments
to compare various implementations of sets of integers (OCaml's Set,
Patricia trees, in both little and big-endian versions, but also various
implementations of red-black trees, including an OCaml-translated
version of Haskell's library, AA trees, etc.)

The outcome was that it was really, really difficult to beat OCaml's
Set. OCaml's Set is a version of AVLs where the heights of the two
subtrees can be at most 2, which appears to be an excellent compromise
between the time spent to rebalance and the maximal height of the trees
(and thus the time spent traversing them in the worst case).

In particular, Patricia trees are supposed to be very good at operations
like "union" (at least that what is suggested by Okasaki and Gill's
title) but I was not observing any major benefit. In some situations,
the union was even less efficient than the one from OCaml's Set.

I kept using my Patricia trees because (1) this is a neat data structure
and (2) in some cases, being able to compare/hash Patricia trees with
OCaml's polymorphic built-in functions is convenient. (Though you may
consider for good reasons that using OCaml's built-in equality is
dangerous and I know some OCaml programmers are simply ruling it out.)

To conclude: hash-consing is definitely worth doing in many situations
(with *huge* benefits in terms of time and space, sometimes both at the
same time) but Patricia trees are not bringing much more improvement.

I'm sorry if you wasted time by porting this part of the implementation
as well. Using other sets from F# library is definitely fine.

--
Jean-Christophe

**Comment by backtracking** [comment]
Regarding points 1 and 2, I kind of remember I was suggested to do so by
people more knowledgeable in the OCaml's GC than myself. (But now that
I'm looking for the emails, I can't find them.)

Note that a shallow copy is a constant time operation.

To answer your question, that would definitely work fine without the
shallow copy.

Regarding point 3, your argument sounds right and it looks like I simply
missed this optimization. Thanks for pointing this out.

--
Jean-Christophe

**Comment by mrakgr** [comment]
Thank you very much for answering all my questions - apart from whether `unsigned_lt` can be replaced with standard comparisons by making the node tags unsigned ints, but I am mostly sure that the answer to that is yes anyway. You've been very helpful.

Also thanks for writing that paper and putting the code out here. It will definitely make a difference to Spiral, the language I am working on.

**Comment by backtracking** [comment]
Sorry for missing that question.

Yes it is definitely simpler if you can use unsigned integers (there are
no in OCaml), hence the name of "unsigned_lt" as you guessed.

--
Jean-Christophe

**Comment by mrakgr** [comment]
Sorry to barge in again, but I thought I should note this here.

On [line 121](https://github.com/backtracking/ocaml-hashcons/blob/master/hashcons.ml#L121), there really should be a comparison between the hkeys. `| Some v when v.node = d ->` should be `| Some v when v.hkey = hkey && v.node = d ->`. Right now I am doing performance testing of the hash consing table and am finding that this makes a significant difference to performance. Adding this check makes the table as fast as the built-in .NET dictionary for hash consing AST nodes.

Yesterday during testing I've been running into all sorts of inexplicable errors, no doubt caused by my shoddy porting effort, so I've redesigned it to be much leaner while staying true to the basic design as done by you. I've also done the optimization for keeping track of the last empty bucket. Since what I have now in [F# port](https://github.com/mrakgr/Hash-Consing) repo does not work, I will replace it with the minimalist implementation that I have now and remove the Patricia trees since they are less convenient than the built-in map and I do not want to keep around code I haven't tested myself nor intend on using.

That should be it, have a nice day.

**Comment by backtracking** [comment]
Indeed that's an optimization you could do. Since hkey is not yet
considered modulo the size of the table, it could be the case that two
values in the same bucket have different hkeys, and you save the
equality test. And indeed a structural equality test with = can be
costly, as it traverses terms that can be arbitrarily large.

But in practice, this is not the equality you are using when performing
hash-consing. Please refer to the paper mentioned in the README, that is

  https://www.lri.fr/~filliatr/ftp/publis/hash-consing2.pdf

As you'll see in that paper (bottom-right of page 1), you can take
advantage of the fact that sub-terms are already hash-consed to perform
physical equality == on sub-terms when defining your equality.

Which means that in practice, when performing hash-consing, you won't be
using the implementation based on structural equality, but rather the
functorial interface with your own equality defined as explained above.
And that equality runs in constant time. So there is little gain in
comparing hkey values first.

Hope this helps,
--
Jean-Christophe
